# Data Science Tools and Ecosystem

In this notebook, Data Science Tools and Ecosystem are summarized.

<b>Objectives:</b> 
- List popular languages for Data Science.
- List popular packages for Data Science.
- List popular Data Science Tools
- Demonstrate some mathematical operations

Some of the popular languages that Data Scientists use are:
1. Python
2. R
3. SQL

Some of the commonly used libraries used by Data Scientists include:
1. Scikit-learn
2. Pandas
3. Numpy

| Data Science Tools             |
|--------------------------------|
| Jupyter Notebook               |
| VS Code with Python extensions | 
| RStudio                        |


### Below are a few examples of evaluating arithmetic expressions in Python

In [5]:
# This a simple arithmetic expression to mutiply then add integers.
(3*4)+5

17

In [6]:
# This will convert 200 minutes to hours by diving by 60
200 / 60

3.3333333333333335

## Author
Charlie Saunders

In [2]:
 '1'+'2'

'12'

In [3]:
"abc".upper()

'ABC'

In [7]:
A=[1,2,3,4,5]
B=A[:]
B

[1, 2, 3, 4, 5]

In [5]:
{"a":1,"b":2}.keys()

dict_keys(['a', 'b'])

In [8]:
"a"=="A"

False

In [9]:
for x in range(0, 3):
    print(x)

0
1
2


In [10]:
 len([sum([1,1,1])])

1

In [11]:
x = "Go" 
if x == "Go": 
    print('Go') 
else: 
    print('Stop') 
print('Mike')

Go
Mike


In [12]:
x="a"
2*x

'aa'

In [14]:
    import numpy as np
    a=np.array([-1,1]) 
    b=np.array([1,1]) 
    np.dot(a,b) 

np.int64(0)

In [17]:
X=np.array([[1,0],[0,1]])

Y=np.array([[2,2],[2,2]]) 

Z=np.dot(X,Y) 

In [19]:
X

array([[1, 0],
       [0, 1]])

In [21]:
Y

array([[2, 2],
       [2, 2]])

In [20]:
Z

array([[2, 2],
       [2, 2]])

In [1]:
for i in range(1,5): 

      if (i!=2):  

          print(i)

1
3
4


In [4]:
import numpy as np

a=np.array([0,1,0,1,0]) 
b=np.array([1,0,1,0,1]) 
a/b 

C:\Users\wavey\AppData\Local\Temp\ipykernel_36256\1685466869.py:5: RuntimeWarning: divide by zero encountered in divide
  a/b


array([ 0., inf,  0., inf,  0.])

In [6]:


a=np.array([1,1,1,1,1]) 
a+10




array([11, 11, 11, 11, 11])